<div class="page-header">
    <h3>Bienvenue dans  votre espace de travail. </h3>
    <h5>MasterBook: Une application de gestion, de partage et d'&eacute;changes des documents</h5>
</div>
<div class="col-md-4">
	<div class="head clearfix">
		<div class="isw-list">
		</div>
		<h1>
			Modules de l'application
		</h1> 
	</div>
	<div class="block news scrollBox">
		<div class="scroll mCustomScrollbar _mCS_1" style="height: 270px;">
			<div class="mCustomScrollBox mCS-light" id="mCSB_1" style="position:relative; height:100%; overflow:hidden; max-width:100%;">
				<div class="mCSB_container" style="position:relative; top:0;">
					<div class="item">
						<a href="javascript:void(0)" style="text-decoration: underline;">Gestion des Fiches Visiteurs :</a>
						<p>
							Enregistrer les visites des clients et les personnes  demand&eacute;es ou contact&eacute;.<br/>
							Visualiser ces visites.
						</p> 
					</div>
					   <div class="item">
						<a href="javascript:void(0)" style="text-decoration: underline;">Gestion des Courriers :</a>
						<p>
							 Sauvegarder tous les courriers d&eacute;part et arriv&eacute;es, attach&eacute; les fichiers et transferer les courriers arriv&eacute;s aux utilisateurs interess&eacute;s.
						</p> 
					</div>
					<div class="item">
						<a href="javascript:void(0)" style="text-decoration: underline;">La messagerie :</a>
						<p>
							Echanges des messages, cr&eacute;e des nouveaux messages, lire des messages recus et gerer les courriers recommand&eacute;.
						</p> 
					</div>
					<div class="item">
						<a href="javascript:void(0)" style="text-decoration: underline;">Enregistrement des contacts :</a>
						<p>
							Enregistrer des repertoires de contact par groupe.
						</p> 
					</div>
					<div class="item">
						<a href="javascript:void(0)" style="text-decoration: underline;">Le EMAILING :</a>
						<p>
							Envoy&eacute; des emails à vos partenaires.
						</p> 
					</div>
					<div class="item">
						<a href="javascript:void(0)" style="text-decoration: underline;">Paramettrage</a>
						<p>
							Gestion de la configuration du systeme. Module reserv&eacute; aux administrateurs et au d&eacute;partement de gestion de l'application
						</p> 
					</div>
				</div> 
			</div>
		</div>
	</div>
</div>
<br/>

<table cellpadding="0" cellspacing="0" width="100%">     
    <tbody>
    	<tr> 
    		<td style="width: 10%"> 
    		</td>
    		<td style="width: 50%">
    			<div class="info">                                                                
				    <ul class="rows"> 
				    <div class="head clearfix">
                            <div class="isw-favorite"></div>
                            <h1>A PROPOS</h1>
                        </div>

				        <li>
				            <div class="title">Nom:</div>
				            <div class="text">MasterBook</div>
				        </li>
				        <li>
				            <div class="title">Soci&eacute;t&eacute;:</div>
				            <div class="text">D&eacute;velopp&eacute; par <a href="http://www.mastersolut.com" target="_blank">MasterSolut</a> </div>
				        </li>
				        <li>
				            <div class="title">Domaine:</div>
				            <div class="text">Ing&eacute;nerie des besions iinformatiques</div>
				        </li>
				        <li>
				            <div class="title">Contact:</div>
				            <div class="text"> (00228) 90 33 74 53 / 99 43 98 46 </div>
				        </li>
				        <li>
				            <div class="title">Email:</div>
				            <div class="text">
				            <a href="mailto:mastersolut@mastersolut.com">mastersolut@mastersolut.com</a></br>
				            <a href="mailto:mastersolut24@gmail.com">mastersolut24@gmail.com</a>
				            					
				            </div> 
				        </li>
				        <li>
				            <div class="title">Version :</div>
				            <div class="text">
				            	</strong> 1.0</strong>
							</div>
				        </li>
				        <li> 
				            <div class="text">
				            	</strong> MasterSolut © 2017.
								Tous droits r&eacute;serv&eacute;s. 
								<a href="http://www.mastersolut.com" target="_blank">www.mastersolut.com</a>
									         </strong>
							</div>
				        </li>
				                           
				    </ul>                                                      
				</div>          
    		</td>
    		<td style="width: 30%"> 
    		</td>
    	</tr>
	</tbody>
</table> 
           